- name: openconfig-policy-forwarding
  docs:
    - yang/policy-forwarding/openconfig-pf-srte.yang
    - yang/policy-forwarding/openconfig-policy-forwarding.yang
  build:
    - yang/policy-forwarding/openconfig-pf-srte.yang
    - yang/policy-forwarding/openconfig-policy-forwarding.yang
  run-ci: true
