- name: openconfig-network-instance-srte-policy
  docs:
    - yang/network-instance/openconfig-network-instance-types.yang
    - yang/network-instance/openconfig-network-instance.yang
    - yang/policy-forwarding/openconfig-pf-network-instances.yang
  build:
    - yang/network-instance/openconfig-network-instance.yang
    - yang/policy-forwarding/openconfig-pf-srte.yang
    - yang/policy-forwarding/openconfig-pf-network-instances.yang
  run-ci: true
